### PR TITLE
fix: Fixed categorical colors being incorrect in viewport

### LINKED ISSUE #626: Categorical colors are incorrect after upgrading Three version
## Description

The new version of Three adds color management, which is causing categorical color ramps to look incorrect.

Image

Image

## Expected Behavior

Viewport colors should match the categorical color preview and scatterplot.

## Reproduction

Open any dataset off of the `feature/3d-viewport-mvp` branch. Run and open any dataset.

## Environment

Windows 11, Chrome

### PR DESCRIPTION
**Pull request by ShrimpCryptid**
Problem
=======
Closes #626, "categorical colors are incorrect after upgrading Three.js version".

*Estimated review size: tiny, <5 minutes*
(Note: static checks will be broken until a dependency in Vol-e core is merged)

Solution
========
- Parses color stops as sRGB hex values instead of directly accessing LinearSRGB values.

## Type of change
Please delete options that are not relevant.

* Bug fix (non-breaking change which fixes an issue)

Steps to Verify:
----------------
1. Open the preview link. Categorical colors should appear in the viewport as they do in the color pickers. https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-633/viewer?collection=https%3A%2F%2Fallencell.s3.amazonaws.com%2Faics%2Fnuc-morph-dataset%2Ftimelapse_feature_explorer_datasets%2Fexploratory_dataset%2Fcollection.json&dataset=Small&feature=trajectory_termination_annotation&bg-key=max_intensity_zprojection_of_lamin_b1&t=199

Screenshots (optional):
-----------------------
| Before | After |
| --- | --- |
| image | image |

### CODE REVIEW

File: src/colorizer/ColorRamp.ts [hunk 1]
```diff
@@ -12,7 +12,16 @@ export default class ColorRamp {
...
-    const dataArr = this.colorStops.flatMap((col) => [col.r, col.g, col.b, 1]);
+    const dataArr = this.colorStops.flatMap((col) => {
+      // Must use getHex() instead of accessing color properties directly (e.g.
+      // `col.r`) so the returned color is in sRGB and not LinearSRGB color
+      // space. See https://threejs.org/manual/#en/color-management.
+      const hex = col.getHex();
+      const r = ((hex >> 16) & 0xff) / 255;
+      const g = ((hex >> 8) & 0xff) / 255;
+      const b = (hex & 0xff) / 255;
+      return [r, g, b, 1];
```
Comment (ascibisz) [inline src/colorizer/ColorRamp.ts:23]: Is there a reason you're doing this manually? I don't know much about this, but I looked at the link and saw they have converters like `.convertLinearToSRGB()`, would that work in this case?

Comment (ShrimpCryptid) [reply src/colorizer/ColorRamp.ts]: Oop, great catch! Updated this code.

**Review by ascibisz — APPROVED** [review]

**Review by frasercl — APPROVED** [review]
