### PR TITLE
fix: Fixes bug where clicking on the canvas did not remove focus from other elements

### LINKED ISSUE #535: Clicking on the viewport should remove focus from inputs
## Description

Sometimes inputs are still focused even after clicking the main canvas viewport. See the video in https://github.com/allen-cell-animated/timelapse-colorizer/pull/532 right around 1:30, where I try to navigate through time with the arrow keys but it instead toggles a radio button I'd previously selected.

## Expected Behavior

Clicking on the viewport should remove focus from inputs or other elements, so that the keyboard shortcuts aren't blocked or don't cause unintentional changes.

## Reproduction

See above video.

## Environment

Windows 11, Chrome

### PR DESCRIPTION
**Pull request by ShrimpCryptid**
Problem
=======
Closes #535, "clicking on viewport should remove focus from other elements."

*Estimated review size: tiny, <5 minutes*

Solution
========
- Clicking or dragging on the canvas now blurs focus from other elements.
## Type of change
* Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by ascibisz — APPROVED** [review]
I don't know much about the world of MouseEvents, but looks good to me! I appreciate the comments in the code :)

File: src/components/CanvasWrapper.tsx [hunk 1]
```diff
@@ -506,7 +506,14 @@ export default function CanvasWrapper(inputProps: CanvasWrapperProps): ReactElem
   }, []);
 
   const onMouseDown = useCallback((event: MouseEvent): void => {
-    event.preventDefault(); // Prevent text selection
+    // Prevent the default behavior for mouse clicks that would cause text
+    // selection, but keep the behavior where focus is removed from other
+    // elements.
+    event.preventDefault();
+    if (document.activeElement instanceof HTMLElement) {
+      document.activeElement.blur();
```
Comment (toloudis) [inline src/components/CanvasWrapper.tsx:514]: will it blur itself too?

**Review by toloudis — APPROVED** [review]
