### PR TITLE
fix: URL is synced after initial load

### LINKED ISSUE #615: URL does not update after the initial dataset load
## Description

The URL doesn't update after the initial dataset is loaded to capture all existing settings, and only updates once state changes again post-load. (e.g. the user changed tabs or color ramps or something).

TECHNICALLY this shouldn't cause any incorrect behavior, since any state that's not defined in the URL will just use the default values, but it's a little strange.

## Expected Behavior

The URL should update with all current viewer state once after the initial dataset load.

## Reproduction

- Open the preview link: https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-614/viewer?dataset=https://arcade-working-bucket.s3.us-west-2.amazonaws.com/0tfe/crawling_agents_interaction_tfe_demo/manifest.json&color=fabio_crameri-romao
- Observe that the URL does not update until after you interact with the the UI again.

## Environment

_Any additional information about your environment. E.g. OS version, python version, browser etc._

### PR DESCRIPTION
**Pull request by ShrimpCryptid**
Problem
=======
Closes #615, "URL does not update after initial load."

This fixes a bug where the URL would not be synced after initial load, and would not update until a state update was triggered. This change ensures that URL contains all current state information right after the first load.

*Estimated review size: tiny, <5 minutes*

Solution
========
- Fixed types on `makeDebouncedCallback`.
- Triggered a URL sync after the initial dataset is loaded.

## Type of change
* Bug fix (non-breaking change which fixes an issue)

Steps to Verify:
----------------
1. Open the preview link here: https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-623/viewer?dataset=https://raw.githubusercontent.com/allen-cell-animated/colorizer-data/refs/heads/main/documentation/getting_started_guide/example/processed_dataset/manifest.json

The URL should be changed from this:
```
https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-623/viewer
?dataset=https://raw.githubusercontent.com/allen-cell-animated/colorizer-data/refs/heads/main/documentation/getting_started_guide/example/processed_dataset/manifest.json
```
to this:
```
https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-623/viewer
?dataset=https%3A%2F%2Fraw.githubusercontent.com%2Fallen-cell-animated%2Fcolorizer-data%2Frefs%2Fheads%2Fmain%2Fdocumentation%2Fgetting_started_guide%2Fexample%2Fprocessed_dataset%2Fmanifest.json
&feature=area&t=0&color=matplotlib-cool&keep-range=0&range=113.100%2C907.900&palette-key=adobe&path=1
&scalebar=1&timestamp=1&filter-color=dddddd&filter-mode=1&outlier-color=c0c0c0&outlier-mode=1
&outline-color=ff00ff&tab=track_plot&scatter-range=all&bg=0&bg-brightness=100&bg-sat=100&fg-alpha=50
&vc=0&vc-key=_motion_&vc-color=000000&vc-scale=4&vc-tooltip=m&vc-time-int=5
```

### CODE REVIEW

File: src/Viewer.tsx [hunk 1]
```diff
@@ -420,6 +420,7 @@ function Viewer(): ReactElement {
         console.error("Failed to load viewer state from URL:", error);
         showAlert(showFailedUrlParseAlert(window.location.href, error as Error));
       }
+      updateUrlParams();
```
Comment (ShrimpCryptid) [inline src/Viewer.tsx:423]: Main bugfix here! This is called after the initial dataset is loaded.

File: src/Viewer.tsx [hunk 2]
```diff
@@ -204,7 +204,7 @@ function Viewer(): ReactElement {
       ) {
         return;
       }
-      updateUrlParams(state);
```
Comment (ShrimpCryptid) [inline src/Viewer.tsx:207]: Previously, there was a bug where `makeDebouncedCallback` would require an argument even if the function took no arguments. I fixed the bug in `store_utils.ts` by updating the types.

File: src/state/utils/store_utils.ts
Comment (ShrimpCryptid) [inline src/state/utils/store_utils.ts:1]: Updated types here so a callback with no arguments will correctly return a function with no arguments.

**Review by meganrm — APPROVED** [review]

**Review by toloudis — APPROVED** [review]
