### PR TITLE
fix: Header and dropdown spacing, tooltip Z-height

### LINKED ISSUE #352: Reverse color ramp tooltip is hidden by header
## Description

image

## Expected Behavior

_What did you expect to happen instead?_

## Reproduction

_A minimal example that exhibits the behavior._

## Environment

_Any additional information about your environment. E.g. OS version, python version, browser etc._

### LINKED ISSUE #358: Dropdown spacing is a little tight
## Description
I noticed the space between dropdowns and the following label are a little tight making the groupings less distinct. The space now is 16px, I recommend 20px. If we are concerned about horizontal width, we could reduce space between labels and their corresponding dropdowns to 4px and keep the spacing between groups at 16.

Screenshot 2024-05-31 at 11 09 43 AM

## Expected Behavior

Screenshot 2024-05-31 at 11 10 03 AM

## Reproduction

_A minimal example that exhibits the behavior._

## Environment

_Any additional information about your environment. E.g. OS version, python version, browser etc._

### LINKED ISSUE #359: Header is too tall
## Description
I think the header accidentally got a little tall??? It's supposed to be around 60px tall and it's currently 71px. Looks like the AICS logo is a bit larger than it needs to be.

Screenshot 2024-05-31 at 11 28 23 AM

## Expected Behavior

Screenshot 2024-05-31 at 11 31 24 AM

If we could reduce top and bottom padding and/or make the AICS logo a bit smaller, that would reduce the height.

## Reproduction

_A minimal example that exhibits the behavior._

## Environment

_Any additional information about your environment. E.g. OS version, python version, browser etc._

### PR DESCRIPTION
**Pull request by ShrimpCryptid**
Problem
=======
Closes #359 and closes #358 , issues raised by Lyndsay! Also closes #352, "reverse ramp button is covered by tooltip".

*Estimated review size: Tiny, 1-5 minutes*

Solution
========
- Increases spacing between dropdowns on the top toolbar.
- Decreases height of header by shrinking logo and removing margins from text.
- Changes Z-height of tooltips to prevent them from being covered by the header.
- Adjusts color map tooltip direction so it doesn't cover over the reverse color map button.

## Type of change
* Bug fix (non-breaking change which fixes an issue)

Screenshots (optional):
-----------------------
image

Preview link: https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-365/

### CODE REVIEW

File: src/components/AppStyle.tsx [hunk 1]
```diff
@@ -355,13 +355,16 @@ export default function AppStyle(props: PropsWithChildren<AppStyleProps>): React
...
               colorBorderSecondary: theme.color.layout.borders,
             },
+            Tooltip: {
+              zIndexPopup: 2000,
+            },
             Divider: {
               marginLG: 0,
             },
             Modal: {
               // Set z-index to 2000 here because Ant sets popups to 1050 by default, and modals to 1000.
```
Comment (meganrm) [inline src/components/AppStyle.tsx:365]: you need to update this comment

**Review by meganrm — APPROVED** [review]
looks good, just need to update the comment to explain your new z index

**Review by frasercl — APPROVED** [review]
Looks good!
