### PR TITLE
fix: Enforce even dimensions on canvas when exporting

### LINKED ISSUE #701: Downloaded MP4 could not be played on Quicktime (Chrome on Mac)
## Description

Reported by @lynwilhelm. An MP4 video exported from a preview build of TFE (most closely TFE v1.5.0) could not be played on Quicktime or Monosnap.

## Expected Behavior

MP4 video should be playable once downloaded.

## Reproduction

_A minimal example that exhibits the behavior._

## Environment

Chrome Mac

### PR DESCRIPTION
**Pull request by ShrimpCryptid**
Problem
=======
Closes #701, "Downloaded MP4 video could not be played in Quicktime."

This change enforces even numbered sizing on the viewport canvas, which allows the AVC1 codec to be chosen more consistently by browsers. AVC1 is generally more widely supported by desktop viewers than VP9 and AV1.

*Estimated review size: tiny, 10 minutes*

Solution
========
- Updated `mp4-muxer` dependency.
- Changed the canvas to always choose the nearest even pixel dimensions.
- Edited some CSS to handle cases where the viewport is wider than its base container.

## Type of change
* New feature (non-breaking change which adds functionality)

Steps to Verify:
----------------
Please do this on Chrome/Safari and not on Firefox, as there's a different bug: #719

1. Open the preview link here:  https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview-internal/pr-717/viewer?collection=https%3A%2F%2Fallencell.s3.amazonaws.com%2Faics%2Fnuc-morph-dataset%2Ftimelapse_feature_explorer_datasets%2Fexploratory_dataset%2Fcollection.json&dataset=Small
3. Go to **Export**, then export an MP4 video of any length.
4. Open the downloaded MP4 video with your desktop viewer.

### CODE REVIEW

File: src/colorizer/recorders/Mp4VideoRecorder.ts [hunk 1]
```diff
@@ -83,6 +83,7 @@ export default class Mp4VideoRecorder extends CanvasRecorder {
               width: width,
               height: height,
             },
+            fastStart: "in-memory",
```
Comment (ShrimpCryptid) [inline src/colorizer/recorders/Mp4VideoRecorder.ts:86]: Needed to specify this with the new version of `mp4-muxer`. More documentation on this here: https://github.com/Vanilagy/mp4-muxer?tab=readme-ov-file#faststart-required

**Review by ascibisz — APPROVED** [review]

**Review by rugeli — APPROVED** [review]
