### PR TITLE
fix: Fixed bug where units would not appear on the UI.

### LINKED ISSUE #382: Feature units do not appear in the UI
## Description

image
Features should have unit included after the numeric value. Also, features in certain areas should be labeled as `feature (unit)`. Currently, the NucMorph team is manually including the units in the feature name.

## Expected Behavior

_What did you expect to happen instead?_

## Reproduction

_A minimal example that exhibits the behavior._

## Environment

_Any additional information about your environment. E.g. OS version, python version, browser etc._

### PR DESCRIPTION
**Pull request by ShrimpCryptid**
Problem
=======
Closes #382, a bug where the feature units from newer datasets did not appear on the UI. This was caused by a mismatch in the key it was retrieving ("units" instead of "unit", which is the expected format based on our documentation: https://github.com/allen-cell-animated/colorizer-data/blob/main/documentation/DATA_FORMAT.md#dataset).

*Estimated review size: small, 5-10 minutes*

Solution
========
- Feature units will now be loaded with the key `unit`.
- Changed thresholds to also refer to `unit` instead of `units` for consistency.
- Older versions of the manifest will now have features remapped from `units` to `unit`.
- Updated unit tests.

## Type of change
* Bug fix (non-breaking change which fixes an issue)

Steps to Verify:
----------------
1. Load these two older datasets, which use the deprecated dataset format (internally use "units"). Mouse over the features dropdown to make sure that the names of the features look identical.
  - FIXED BUILD: https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-383/viewer?collection=https%3A%2F%2Fdev-aics-dtp-001.int.allencell.org%2Fdan-data%2Fcolorizer%2Fdata%2Fcollection.json
  - BROKEN BUILD: https://allen-cell-animated.github.io/timelapse-colorizer/viewer?collection=https%3A%2F%2Fdev-aics-dtp-001.int.allencell.org%2Fdan-data%2Fcolorizer%2Fdata%2Fcollection.json
2. Load this newer dataset (internally uses "unit"). Units should appear in the feature dropdown in the new build but not in the old build.
  - FIXED BUILD: https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-383/viewer?collection=https%3A%2F%2Fdev-aics-dtp-001.int.allencell.org%2Fassay-dev%2Fcomputational%2Fdata%2FEMT_deliverable_processing%2FTranscription_factor_cell_lines%2FVersion_1%2Fcolorizer_output%2FEOMES%2Fcollections_all.json
  - BROKEN BUILD: https://allen-cell-animated.github.io/timelapse-colorizer/viewer?collection=https%3A%2F%2Fdev-aics-dtp-001.int.allencell.org%2Fassay-dev%2Fcomputational%2Fdata%2FEMT_deliverable_processing%2FTranscription_factor_cell_lines%2FVersion_1%2Fcolorizer_output%2FEOMES%2Fcollections_all.json

Screenshots (optional):
-----------------------
image

image

### CODE REVIEW

File: src/colorizer/utils/dataset_utils.ts [hunk 1]
```diff
@@ -106,7 +107,8 @@ export const updateManifestVersion = (manifest: AnyManifestFile): ManifestFile =
       features.push({
         name: featureName,
         data: featurePath,
-        units: featureMetadata?.units || undefined,
+        // Note change from "units" to "unit"
+        unit: featureMetadata?.units || undefined,
```
Comment (ShrimpCryptid) [inline src/colorizer/utils/dataset_utils.ts:111]: Remaps from old metadata format to newer.

**Review by meganrm — APPROVED** [review]

File: src/colorizer/utils/dataset_utils.ts (hunk 1 above)
Comment (frasercl) [reply src/colorizer/utils/dataset_utils.ts:111]: Any reason to check for `featureMetadata?.unit` here as well, or will we definitely only see `units` if we've made it here?

**Review by frasercl — APPROVED** [review]
unit unit unit unit unit
